/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DestinationId = IDL.Nat;
export const Destination = IDL.Record({
  'id' : DestinationId,
  'name' : IDL.Text,
  'overview' : IDL.Text,
  'highlights' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
});
export const TourId = IDL.Nat;
export const DayItinerary = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Tour = IDL.Record({
  'id' : TourId,
  'galleryImages' : IDL.Vec(IDL.Text),
  'startingPrice' : IDL.Nat,
  'destination' : IDL.Text,
  'duration' : IDL.Text,
  'destinationId' : IDL.Opt(DestinationId),
  'name' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'exclusions' : IDL.Vec(IDL.Text),
  'departureDates' : IDL.Vec(IDL.Text),
  'groupSize' : IDL.Text,
  'itinerary' : IDL.Vec(DayItinerary),
});
export const InquiryRequest = IDL.Record({
  'desiredDate' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'tourName' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'groupSize' : IDL.Nat,
});
export const InquiryId = IDL.Nat;

export const idlService = IDL.Service({
  'getDestination' : IDL.Func(
      [DestinationId],
      [IDL.Opt(Destination)],
      ['query'],
    ),
  'getTour' : IDL.Func([TourId], [IDL.Opt(Tour)], ['query']),
  'getToursByDestination' : IDL.Func([IDL.Text], [IDL.Vec(Tour)], ['query']),
  'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'listTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'submitInquiry' : IDL.Func([InquiryRequest], [InquiryId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DestinationId = IDL.Nat;
  const Destination = IDL.Record({
    'id' : DestinationId,
    'name' : IDL.Text,
    'overview' : IDL.Text,
    'highlights' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
  });
  const TourId = IDL.Nat;
  const DayItinerary = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Tour = IDL.Record({
    'id' : TourId,
    'galleryImages' : IDL.Vec(IDL.Text),
    'startingPrice' : IDL.Nat,
    'destination' : IDL.Text,
    'duration' : IDL.Text,
    'destinationId' : IDL.Opt(DestinationId),
    'name' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'exclusions' : IDL.Vec(IDL.Text),
    'departureDates' : IDL.Vec(IDL.Text),
    'groupSize' : IDL.Text,
    'itinerary' : IDL.Vec(DayItinerary),
  });
  const InquiryRequest = IDL.Record({
    'desiredDate' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'tourName' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'groupSize' : IDL.Nat,
  });
  const InquiryId = IDL.Nat;
  
  return IDL.Service({
    'getDestination' : IDL.Func(
        [DestinationId],
        [IDL.Opt(Destination)],
        ['query'],
      ),
    'getTour' : IDL.Func([TourId], [IDL.Opt(Tour)], ['query']),
    'getToursByDestination' : IDL.Func([IDL.Text], [IDL.Vec(Tour)], ['query']),
    'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'listTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'submitInquiry' : IDL.Func([InquiryRequest], [InquiryId], []),
  });
};

export const init = ({ IDL }) => { return []; };