/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayItinerary {
  'day' : bigint,
  'title' : string,
  'description' : string,
}
export interface Destination {
  'id' : DestinationId,
  'name' : string,
  'overview' : string,
  'highlights' : Array<string>,
  'imageUrl' : string,
}
export type DestinationId = bigint;
export type InquiryId = bigint;
export interface InquiryRequest {
  'desiredDate' : string,
  'name' : string,
  'email' : string,
  'tourName' : string,
  'message' : string,
  'phone' : string,
  'groupSize' : bigint,
}
export interface Tour {
  'id' : TourId,
  'galleryImages' : Array<string>,
  'startingPrice' : bigint,
  'destination' : string,
  'duration' : string,
  'destinationId' : [] | [DestinationId],
  'name' : string,
  'inclusions' : Array<string>,
  'highlights' : Array<string>,
  'exclusions' : Array<string>,
  'departureDates' : Array<string>,
  'groupSize' : string,
  'itinerary' : Array<DayItinerary>,
}
export type TourId = bigint;
export interface _SERVICE {
  'getDestination' : ActorMethod<[DestinationId], [] | [Destination]>,
  'getTour' : ActorMethod<[TourId], [] | [Tour]>,
  'getToursByDestination' : ActorMethod<[string], Array<Tour>>,
  'listDestinations' : ActorMethod<[], Array<Destination>>,
  'listTours' : ActorMethod<[], Array<Tour>>,
  'submitInquiry' : ActorMethod<[InquiryRequest], InquiryId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];