/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type InquiryId = bigint;
export interface Destination {
    id: DestinationId;
    name: string;
    overview: string;
    highlights: Array<string>;
    imageUrl: string;
}
export interface InquiryRequest {
    desiredDate: string;
    name: string;
    email: string;
    tourName: string;
    message: string;
    phone: string;
    groupSize: bigint;
}
export interface DayItinerary {
    day: bigint;
    title: string;
    description: string;
}
export interface Tour {
    id: TourId;
    galleryImages: Array<string>;
    startingPrice: bigint;
    destination: string;
    duration: string;
    destinationId?: DestinationId;
    name: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    exclusions: Array<string>;
    departureDates: Array<string>;
    groupSize: string;
    itinerary: Array<DayItinerary>;
}
export type TourId = bigint;
export type DestinationId = bigint;
export interface backendInterface {
    getDestination(id: DestinationId): Promise<Destination | null>;
    getTour(id: TourId): Promise<Tour | null>;
    getToursByDestination(destination: string): Promise<Array<Tour>>;
    listDestinations(): Promise<Array<Destination>>;
    listTours(): Promise<Array<Tour>>;
    submitInquiry(req: InquiryRequest): Promise<InquiryId>;
}
import type { DayItinerary as _DayItinerary, Destination as _Destination, DestinationId as _DestinationId, Tour as _Tour, TourId as _TourId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getDestination(arg0: DestinationId): Promise<Destination | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTour(arg0: TourId): Promise<Tour | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTour(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTour(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToursByDestination(arg0: string): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToursByDestination(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToursByDestination(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDestinations();
            return result;
        }
    }
    async listTours(): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTours();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTours();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: InquiryRequest): Promise<InquiryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
}
function from_candid_Tour_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tour): Tour {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Destination]): Destination | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tour]): Tour | null {
    return value.length === 0 ? null : from_candid_Tour_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DestinationId]): DestinationId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TourId;
    galleryImages: Array<string>;
    startingPrice: bigint;
    destination: string;
    duration: string;
    destinationId: [] | [_DestinationId];
    name: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    exclusions: Array<string>;
    departureDates: Array<string>;
    groupSize: string;
    itinerary: Array<_DayItinerary>;
}): {
    id: TourId;
    galleryImages: Array<string>;
    startingPrice: bigint;
    destination: string;
    duration: string;
    destinationId?: DestinationId;
    name: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    exclusions: Array<string>;
    departureDates: Array<string>;
    groupSize: string;
    itinerary: Array<DayItinerary>;
} {
    return {
        id: value.id,
        galleryImages: value.galleryImages,
        startingPrice: value.startingPrice,
        destination: value.destination,
        duration: value.duration,
        destinationId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.destinationId)),
        name: value.name,
        inclusions: value.inclusions,
        highlights: value.highlights,
        exclusions: value.exclusions,
        departureDates: value.departureDates,
        groupSize: value.groupSize,
        itinerary: value.itinerary
    };
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tour>): Array<Tour> {
    return value.map((x)=>from_candid_Tour_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
